name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "refactor"
      - "test"
  - title: "📚 Documentation"
    labels:
      - "docs"
      - "documentation"

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
