version: "1.x" 
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable:
    - typecheck #TODO: enable typecheck
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unused
    - whitespace

issues:
  max-issues-per-linter: 0
  max-same-issues: 0